DELETE http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Anthony Tran",
    "number": "408-831-8620"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": "408-831-8620"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Anthony Tran",
    "number": ""
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number": ""
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Anthony Tran",
    "number": "543-5432"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Trong Tran",
    "number": "543-5432"
}